version: '3.9'

services:
  web:
    image: nftds
    ports: 
      - "3000:5000"
    env_file: 
      - ./server/.env
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - .mysql.env
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data: